apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-appone-api
  namespace: dotnetcore
  labels:
    app: service-appone-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-appone-api
  template:
    metadata:
      labels:
        app: service-appone-api
    spec:
      containers:
      - name: service-appone-api-demo
        image: 	shaohz/k8s-service-appone:2.0
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: k8s-service-appone
  namespace: dotnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: service-appone-api
