apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-apptwo-api
  namespace: dotnetcore
  labels:
    app: service-apptwo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-apptwo-api
  template:
    metadata:
      labels:
        app: service-apptwo-api
    spec:
      containers:
      - name: service-apptwo-api-demo
        #设置环境变量参数
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        image: 	registry.cn-shenzhen.aliyuncs.com/shaohz/k8s-service-apptwo:2.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: shaohz-aliyun-registrykey

---

kind: Service
apiVersion: v1
metadata:
  name: k8s-service-apptwo
  namespace: dotnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: service-apptwo-api
